# Generated by Django 3.2.3 on 2021-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210704_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_popularity',
            field=models.IntegerField(blank=True),
        ),
    ]
